/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { GoogleGenAI } from '@google/genai';

const ai = new GoogleGenAI({
  apiKey: process.env.API_KEY
});


const urlToGenerativePart = async imageUrl => {
  const response = await fetch(imageUrl)
  if (!response.ok) {
    throw new Error(
      `Failed to fetch image: ${response.status} ${response.statusText}`
    )
  }

  const blob = await response.blob()
  const mimeType = response.headers.get('Content-Type') || blob.type

  if (!mimeType) {
    throw new Error('Could not determine MIME type for the image.')
  }

  const base64EncodedDataPromise = new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => {
      if (typeof reader.result === 'string') {
        resolve(reader.result.split(',')[1])
      } else {
        reject(new Error('Failed to read image data as base64 string.'))
      }
    }
    reader.onerror = error => reject(error)
    reader.readAsDataURL(blob)
  })

  return {
    inlineData: {
      data: await base64EncodedDataPromise,
      mimeType
    }
  }
}

export const queryLlm = async ({prompt, image: imageUrl}) => {
  const contentParts = [{text: prompt}]

  if (imageUrl && typeof imageUrl === 'string') {
    try {
      const imagePart = await urlToGenerativePart(imageUrl)
      contentParts.push(imagePart)
    } catch (error) {
      console.error(`Error processing image URL "${imageUrl}":`, error)

    }
  }

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-preview-04-17',
    contents: contentParts,
    config:{
      thinkingConfig: {
        thinkingBudget: 0,
      },
    }
  })
  return response.text
}

export const generateImagesApi = async (prompt, numberOfImages = 1) => {
  if (!prompt || prompt.trim() === "") {
    throw new Error("Prompt cannot be empty.");
  }
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-3.0-generate-002',
      prompt: prompt,
      config: { numberOfImages: Number(numberOfImages), outputMimeType: 'image/jpeg' },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      return response.generatedImages.map(imgObj => ({
        base64: imgObj.image.imageBytes, // This is the base64 string
      }));
    } else {
      // Handle cases where no images might be returned, though API usually errors or returns something.
      console.warn("No images generated by API for prompt:", prompt);
      return []; 
    }
  } catch (error) {
    console.error("Error generating images via API:", error);
    // Re-throw the error to be caught by the calling action
    throw error; 
  }
};
